### ISSUE TITLE
Line Break Prevented Test From Executing

### ISSUE THREAD

**Issue by Schnyle** [learn-co-curriculum/phase-0-css-intro-lab#23]
### Canvas Link

https://learning.flatironschool.com/courses/6601/assignments/219054?module_item_id=510699

### Concern

indexTest.js:26 I believe line 27 needs to be moved up to be a part of line 26, this allowed my tests to execute.

**Comment by jlboba** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved.
Note, however, that if you are working in Canvas the changes may not show up
there, but they will for future students.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
